// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleApplicationTestingMvcSkills.Models;

namespace SimpleApplicationTestingMvcSkills.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210222215657_Seeding-Initial-Data")]
    partial class SeedingInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleApplicationTestingMvcSkills.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Employee ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department")
                        .HasColumnType("int")
                        .HasColumnName("Department ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("navarchar(50)")
                        .HasColumnName("Office Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Employee Name");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Department = 1,
                            Email = "iamtuseTheProgrammer@iamtuse.com",
                            Name = "iamtuse"
                        },
                        new
                        {
                            ID = 2,
                            Department = 3,
                            Email = "wonkulahp@iamtuse.com",
                            Name = "Precious K Wonkulah"
                        },
                        new
                        {
                            ID = 3,
                            Department = 4,
                            Email = "darious@iamtuse.com",
                            Name = "Darious F Wonkulah"
                        },
                        new
                        {
                            ID = 4,
                            Department = 2,
                            Email = "dacious@iamtuse.com",
                            Name = "Dacious F Wonkulah"
                        },
                        new
                        {
                            ID = 5,
                            Department = 3,
                            Email = "dad@iamtuse.com",
                            Name = "Dad S Wonkulah Sr"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
